require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  SuggestExtensions: false
  NewCops: enable

Layout/HashAlignment:
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - '*.gemspec'

Metrics/ParameterLists:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always_true

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

